name: markdownlint
on: [push, pull_request]
jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v38
        with:
          files: '**/*.md'
          separator: ','

      - name: Lint Markdown Documents
        uses: DavidAnson/markdownlint-cli2-action@v11
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          globs: ${{ steps.changed-files.outputs.all_changed_files }}
          separator: ','
